config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_prefix: 'd'

  root 'users#index'

  resources :users
  resources :tests, except: [:show]

  namespace :api, format: 'json' do
    namespace :v1 do
      mount_devise_token_auth_for 'User', at: '/auth'

      resources :tests, only: [:index, :show]
      resources :applicants, only: [:create]
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <button class="navbar-toggler text-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav align-items-end ml-auto">
        <li class="nav-item text-nowrap">
          <%= link_to "Users", users_path, class: "nav-link #{active_class('users')}" %>
        </li>
        <li class="nav-item text-nowrap border-lr">
          <%= link_to "Tests", tests_path, class: "nav-link #{active_class('tests')}" %>
        </li>
        <li class="nav-item text-nowrap">
          <%= link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodingChallenge1300</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if user_signed_in? %>
  <%= render 'layouts/navbar' %>
<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
      <% end %>

      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>